name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
      - stable

jobs:
  build-for-linux-amd64:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        abi:
          - glibc
          - musl
        otp:
          - 28
          - 29
        platform:
          - amd64

    steps:
      - uses: actions/checkout@v6

      - name: Precompile and test
        uses: dagger/dagger-for-github@v8.4.1
        with:
          version: 0.20.6
          args: >-
            ci \
              --src-dir . \
              --platform-name linux/${{ matrix.platform }} \
              --abi ${{ matrix.abi }} \
              --otp ${{ matrix.otp }} \
            export \
              --path . \
              --allowParentDirPath

      - name: Upload files
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.platform }}-${{ matrix.abi }}-otp${{ matrix.otp }}
          path: pdfium-nif-*

  build-for-linux-arm64:
    runs-on: ubuntu-24.04-arm

    strategy:
      matrix:
        abi:
          - glibc
          - musl
        otp:
          - 28
          - 29
        platform:
          - arm64

    steps:
      - uses: actions/checkout@v6

      - name: Precompile and test
        uses: dagger/dagger-for-github@v8.4.1
        with:
          version: 0.20.6
          args: >-
            ci \
              --src-dir . \
              --platform-name linux/${{ matrix.platform }} \
              --abi ${{ matrix.abi }} \
              --otp ${{ matrix.otp }} \
            export \
              --path . \
              --allowParentDirPath

      - name: Upload files
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.platform }}-${{ matrix.abi }}-otp${{ matrix.otp }}
          path: pdfium-nif-*

  build-for-macos:
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build
        run: |
          pushd custom
          ./build-for-mac.sh macos arm64 28.4.2
          ./build-for-mac.sh macos x86_64 28.4.2
          ./build-for-mac.sh macos arm64 29.0.1
          ./build-for-mac.sh macos x86_64 29.0.1
          popd

      - name: Upload files
        uses: actions/upload-artifact@v7
        with:
          name: macOS-builds
          path: custom/pdfium-nif-*
